# Generated by Django 3.0.8 on 2020-08-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellido')),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('sexo', models.CharField(max_length=1, verbose_name='Sexo')),
                ('user', models.CharField(max_length=200, verbose_name='Sexo')),
                ('user_mod', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
